Models/Categoria.cs
namespace efcurso.Models
{
    public class Categoria
    {
        public int Id {get; set;}
        public string Nome {get; set;}
        public override string ToString(){
            return "Id: " + this.Id + " Nome: " + this.Nome;
        }
    }
}

Models/ErrorViewModel.cs
using System;

namespace efcurso.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Funcionario.cs
namespace efcurso.Models
{
    public class Funcionario
    {
        public int Id {get; set;}
        public string Nome {get; set;}
        public float Salario {get;set;}
        public string Cpf {get;set;}
    }
}

Models/Produto.cs
namespace efcurso.Models
{
    public class Produto
    {
        public int Id {get; set;}
        public string Nome {get; set;}
        public virtual Categoria Categoria {get; set;}

        public override string ToString()
        {
            return "Id: " + this.Id + "Nome: " + this.Nome + " Categoria: [" + this.Categoria.ToString() + "] ";
        }
    }
}

Controllers/FuncionariosController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using efcurso.Models;
using efcurso.Database;

namespace efcurso.Controllers
{
    public class FuncionariosController : Controller
    {
        private readonly ApplicationDBContext database;

        public FuncionariosController(ApplicationDBContext database)
        {
            this.database = database;
        }

        public IActionResult Index()
        {
            var funcionarios = database.Funcionarios.ToList();
            return View(funcionarios);
        }
        public IActionResult Cadastrar()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
            Funcionario funcionario = database.Funcionarios.First(registro => registro.Id == id);
            return View("Cadastrar", funcionario);
        }

        public IActionResult Deletar(int id)
        {
            Funcionario funcionario = database.Funcionarios.First(registro => registro.Id == id);
            database.Funcionarios.Remove(funcionario);
            database.SaveChanges();
            return RedirectToAction("Index");

        }

        [HttpPost]
        public IActionResult Salvar(Funcionario funcionario)
        {
            if(funcionario.Id == 0){
                database.Funcionarios.Add(funcionario);
            }else{
                Funcionario funcionarioDoBanco = database.Funcionarios.First(registro => registro.Id == funcionario.Id);
                funcionarioDoBanco.Nome = funcionario.Nome;
                funcionarioDoBanco.Salario = funcionario.Salario;
                funcionarioDoBanco.Cpf = funcionario.Cpf;
            }

            
            database.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using efcurso.Models;
using efcurso.Database;
using Microsoft.EntityFrameworkCore;

namespace efcurso.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDBContext database;
        public HomeController(ApplicationDBContext database){
            this.database = database;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Teste()
        {
            /*Categoria c1 = new Categoria();
            c1.Nome = "Categoria 1";
            Categoria c2 = new Categoria();
            c2.Nome = "Categoria 2";
            Categoria c3 = new Categoria();
            c3.Nome = "Categoria 3";
            Categoria c4 = new Categoria();
            c4.Nome = "Categoria 4";

            List<Categoria> catList = new List<Categoria>();
            catList.Add(c1);
            catList.Add(c2);
            catList.Add(c3);
            catList.Add(c4);

            database.AddRange(catList);
            database.SaveChanges();
            */
            var listadeCategorias = database.Categorias.Where(cat => cat.Nome.Equals("Categoria")).ToList();
            Console.WriteLine("==================== Categorias ================");

            listadeCategorias.ForEach(categoria =>{
                Console.WriteLine(categoria.ToString());
                
            });

            Console.WriteLine("====================================");

            return Content("dadoos salvos");
        }

        public IActionResult Relacionamento()
        {
            /**
            Produto p = new Produto();
            p.Nome = "Doritos";
            p.Categoria = database.Categorias.First(c => c.Id == 1);

            Produto p2 = new Produto();
            p2.Nome = "Frango";
            p2.Categoria = database.Categorias.First(c => c.Id == 1);

            Produto p3 = new Produto();
            p3.Nome = "Bolo";
            p3.Categoria = database.Categorias.First(c => c.Id == 2);

            database.Add(p);
            database.Add(p2);
            database.Add(p3);
            

            var listadeProdutos = database.Produtos.Include(p => p.Categoria).ToList();
            listadeProdutos.ForEach(produto => {
                Console.WriteLine(produto.ToString());
            });
            */
            var listaDeProdutosDeCategoria = database.Produtos.Include(p => p.Categoria).Where(p => p.Categoria.Id == 1).ToList();
            listaDeProdutosDeCategoria.ForEach(produto => {
                Console.WriteLine(produto.ToString());
            });
            return Content("Relacionamento");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Funcionarios/Cadastrar.cshtml
@model efcurso.Models.Funcionario

<h2></h2>

<form class="form-horizontal" asp-controller="Funcionarios" asp-action="Salvar" method="POST">
    <input type="hidden" asp-for="Id">
    <div class="form-group">
        <label for="Nome">Nome</label>
        <input type="text" class="form-control" asp-for="Nome" placeholder="Digite o Nome">
    </div>
    <div class="form-group">
        <label for="Salário">Salário</label>
        <input type="number" class="form-control" asp-for="Salario" placeholder="Digite o Salário">
    </div>
    <div class="form-group">
        <label for="Cpf">Cpf</label>
        <input type="text" class="form-control" asp-for="Cpf" placeholder="Digite o CPF">
    </div>
    <button class="btn btn-success">Cadastrar</button>
</form>

Views/Funcionarios/Index.cshtml
@model IEnumerable<efcurso.Models.Funcionario>

<h2>Todos os Funcionários</h2>
<a href="/Funcionarios/Cadastrar" class="btn btn-success">Novo</a>
<hr>
@foreach (var funcionario in Model)
{
    <p>@funcionario.Cpf</p>
    <p>@funcionario.Nome</p>
    <p>@funcionario.Salario</p>
    <a href="/Funcionarios/Editar/@funcionario.Id" class="btn btn-success">Editar</a>
    <a href="/Funcionarios/Deletar/@funcionario.Id" class="btn btn-danger">Deletar</a>
    <hr>
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - efcurso</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">efcurso</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - efcurso - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>